# Generated by Django 3.2.18 on 2023-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_categorymodel_pagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
