# Generated by Django 3.2.18 on 2023-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_bookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
