# Generated by Django 3.2.18 on 2023-04-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_authormodel_bookmodel_publishermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookModel',
        ),
    ]
