# Generated by Django 3.2.18 on 2023-04-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.authormodel', to_field='fname')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.publishermodel', to_field='name')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
