# Generated by Django 2.1 on 2023-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(choices=[('thriller', 'thriller'), ('horror', 'horror'), ('romance', 'romance')], default='thriller', max_length=100)),
            ],
        ),
    ]
