# Generated by Django 2.1 on 2023-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='borrowed',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
