# Generated by Django 2.1 on 2023-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmodel_borrowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('issue_date', models.CharField(max_length=20)),
            ],
        ),
    ]
